var config = {};

config.dates = {};
config.auth = {};

//in a normal situation this whould be taken from users device settings
config.dates.timezone = "Europe/Warsaw";
//not sure if this will be used, put it just in case
config.auth.token = `eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6IjEifQ
    .eyJhdWQiOiJodHRwczovL2FwaS5hbWF6b25hbGV4YS5jb20iLCJpc3MiOiJBbGV4YV
    NraWxsS2l0Iiwic3ViIjoiYW16bjEuYXNrLnNraWxsLjhlOTNhOTI2LTBhMmEtNGZkZ
    i1iMWRiLWZkMjE2MTc5ZDg1YSIsImV4cCI6MTYwNjUyMDg2NCwiaWF0IjoxNjA2NTE3
    MjY0LCJuYmYiOjE2MDY1MTcyNjQsInByaXZhdGVDbGFpbXMiOnsiaXNEZXByZWNhdGV
    kIjoidHJ1ZSIsImNvbnNlbnRUb2tlbiI6IkF0emF8SXdFQklESWlHZ1d0Vnhpay1HUE
    JaMUwxeXJ6QU5nVktkYzVYUFY2VUJtS0lfUGQwWFNJYV82S3dnREZrT3A4X0xvTkE3V
    mU1MTR0Q0NHS280VHZnblNSMjFPTHhhWkFNVS1QWFJ1azVjdUZLTzVGTzBCVHZpOWts
    M2ZzTmhSa3hHQzV6WGhCV04wU1pwdjZHQ1R2RjN5SXBGTmwxbTExYW9RV24tZ0QzaHl
    qemFVRU1VQ0tQenpQdExDR2pvd0Y1TGdyMWFCUlU4bWlZTVVVR3VnZzJES3hhSDBfc2
    JSLWlsNjZFbzJScXVBMnFzbHZrNkkxWVVJVDVYMXI1UDZqTldCeGF3ell1TDRqRkVtd
    DY4NVdqbnM2a1VlaTlYZVNjU0dzb1gycnRKMTRXdUR3S2p3IiwiZGV2aWNlSWQiOiJh
    bXpuMS5hc2suZGV2aWNlLkFINzVLWUI2N0JYTVFXNFNSVUVUSExSUkZaNFY3VURJSE1
    EWE5DT082S1JIVU9WMlRLSkRHWEUyWkpZSzdQT0RSNTVLTDVBVkdTM0VYWkZHMlFJNF
    FXR1lJUDNIM1ZHUlpEVFlaTUpERVRVVk9SVk1YSkhEQTVQWTNYSzZZWkpZNUJCTDJGS
    ElKRDVQR1NJT1ZBTkE3VVROUVdPVkpVNTVYVUFGR1daVk1CTFJQSktONUlQTk8iLCJ1
    c2VySWQiOiJhbXpuMS5hc2suYWNjb3VudC5BRUpFVVkyTllJTENVTzZaUjJOT0cyTU5
    LUzI2S0xSRVFMT1ZQRkhERENQNU5CS1E1QkJGU1lSR0hMS09HV1BYRFdPRURYU1dET1
    Y0VExYVktTQVBXM1lYNENMTERFSElHUUY1TUlSUDNHV1FGT0ZVWDVNUjNJWlRYWllUT
    VpEQ1NTVDJWVzVFQkJIM0FQUFBBVEdXUU5MTjdEWERFQTNHNU41RUdUM0tZRkhBWUpF
    V01SVlBHTkhEVzM1NUpONTNIN0RBS04yTVNKQTVUNEkifX0.kPiOYjfEMCxRM8YaqvG
    zkUy7dqQl4eLWZbBrbrYu79iemvIKJbXYe8kim7GjmVvRZ0kngxeWn-N7Qy1qHzVvHI
    l-1-3vf8lizok1BfNsk9fPN0-5a7ua7x9SYWyPbSxCLllqcoVyj32wWIDdOUsPu3lu3
    jXQC7nTUbP2qSG0GFEdEERlbjN3_ke7q_YbJQ1sxcpKLEbjTkECIFPTKgXyc83kcY3m
    7uiuFfZuuIc3BOOvLlnQPTE81RXR1CqmQeFyCOmuJeSJoHPja8FURGn9pbIl-hFIgj-
    yP9enS0Es2xcEFxOL3avTbjHA7mxV2dHdyNW1mrl9M7bQrkzZtkAAKw`;

module.exports = config;